### composer install
### php artisan migrate:fresh
### php artisan key:generate
### php artisan serve
### php artisan storage:link
### Categories
## GET
POST http://localhost:8000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "jane.smith@store.com",
    "password": "password123"
}


###
GET http://localhost:8000/api/products
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/sales/stats
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/stores
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/categories
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
###
GET http://localhost:8000/api/customers/stats
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/customers
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/sales
Accept: application/json
Authorization: Bearer 5|zts66s1Smv94odqXuU8JVw2p008ssvht0gqYOR9A3b6bc1d3
###
GET http://localhost:8000/api/customers/stats
Accept: application/json
###
GET http://localhost:8000/api/customers/1/addresses
Accept: application/json
###
GET http://localhost:8000/api/dashboard/stats
Accept: application/json
###
GET http://localhost:8000/api/orders
Accept: application/json
###
GET http://localhost:8000/api/products
Accept: application/json
###
GET http://localhost:8000/api/products/5/low-stock
Accept: application/json
###
GET http://localhost:8000/api/sales
Accept: application/json
###
GET http://localhost:8000/api/sales
Accept: application/json
###
GET http://localhost:8000/api/stores
Accept: application/json
